#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

/wait-for-selenium http://selenium:4444/wd/hub

# Use $1 to get the first argument passed to the script
scrapy crawl $1 --output /app/data/output.csv
