#!/bin/bash
# compose/start

set -o errexit
set -o pipefail
set -o nounset

# Run the main Python script/module
# Adjust the command below if your entry point is different (e.g., a main.py or Flask/Django app)
python linkedin/login.py